font_family JetBrainsMono Nerd Font 
font_size  13

shell                          fish  
shell_integration              enabled

cursor_shape beam
cursor_blink_interval 0
window_padding_width 12

disable_ligatures              yes
enable_audio_bell              no

remember_window_size           no
background_opacity             0.92
scrollbar_track_opacity        0
scrollbar_track_hover_opacity  0

# Closing confirmation 
confirm_os_window_close        0

sync_to_monitor                no


# The basic colors
foreground #E3E9FF
background #0A1024
selection_foreground    #24273a
selection_background    #f4dbd6

# Cursor colors
cursor #7C91FF
cursor_text_color background

# Scrollbar colors
scrollbar_handle_color  #939ab7
scrollbar_track_color   #494d64

# URL color when hovering with mouse
url_color #7C91FF

copy_on_select yes

strip_trailing_spaces smart

mouse_hide_wait 1.5

repaint_delay 10

input_delay 3


scrollback_lines 50000
# Kitty window border colors
active_border_color #7096FF
inactive_border_color #233A68
bell_border_color       #eed49f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #181926
active_tab_background   #c6a0f6
inactive_tab_foreground #cad3f5
inactive_tab_background #1e2030
tab_bar_background      #181926

# Colors for marks (marked text in the terminal)
mark1_foreground #24273a
mark1_background #b7bdf8
mark2_foreground #24273a
mark2_background #c6a0f6
mark3_foreground #24273a
mark3_background #7dc4e4

# The 16 terminal colors

# black
color0 #494d64
color8 #5b6078

# red
color1 #ed8796
color9 #ed8796

# green
color2  #a6da95
color10 #a6da95

# yellow
color3  #eed49f
color11 #eed49f

# blue
color4  #8aadf4
color12 #8aadf4

# magenta
color5  #f5bde6
color13 #f5bde6

# cyan
color6  #8bd5ca
color14 #8bd5ca

# white
color7  #b8c0e0
color15 #a5adcb
