```conf
# ============================================
# BACKGROUND
# ============================================

background {
    path = /home/sharvesh/.cache/current_wallpaper
    
    blur_passes = 5
    blur_size = 8

    noise = 0.012

    contrast = 1.15
    brightness = 0.85

    vibrancy = 0.30
    vibrancy_darkness = 0.20
}

# ============================================
# Glass Panel
# ============================================

shape {
    size = 520, 420

    color = rgba(20,20,20,0.30)

    rounding = 30

    border_size = 2
    border_color = rgba(255,255,255,0.12)

    position = 0,40

    halign = center
    valign = center
}

# ============================================
# TIME
# ============================================

label {

    text = cmd[update:1000] echo "$TIME"

    color = rgb(255,255,255)

    font_size = 118
    font_family = JetBrainsMono Nerd Font

    position = 0,155

    halign = center
    valign = center

    shadow_passes = 5
    shadow_size = 8
}

# ============================================
# DAY
# ============================================

label {

    text = cmd[update:60000] date "+%A"

    color = rgba(255,255,255,0.90)

    font_size = 26

    font_family = JetBrainsMono Nerd Font

    position = 0,78

    halign = center
    valign = center
}

# ============================================
# DATE
# ============================================

label {

    text = cmd[update:60000] date "+%d %B %Y"

    color = rgba(255,255,255,0.65)

    font_size = 18

    font_family = JetBrainsMono Nerd Font

    position = 0,50

    halign = center
    valign = center
}

# ============================================
# PASSWORD FIELD
# ============================================

input-field {

    size = 180,40

    outline_thickness = 0

    rounding = -1

    inner_color = rgba(255,255,255,0.96)

    font_color = rgb(20,20,20)

    dots_size = 0.30
    dots_spacing = 0.52
    dots_center = true

    hide_input = false

    check_color = rgb(166,227,161)
    fail_color = rgb(243,139,168)

    fail_transition = 250

    position = 0,-25

    halign = center
    valign = center
}

# ============================================
# USER
# ============================================

label {

    text = $USER

    color = rgba(255,255,255,0.55)

    font_size = 18

    font_family = JetBrainsMono Nerd Font

    position = 0,-95

    halign = center
    valign = center
}

# ============================================
# HINT
# ============================================

label {

    text = "Press ESC to switch user"

    color = rgba(255,255,255,0.35)

    font_size = 14

    font_family = JetBrainsMono Nerd Font

    position = 0,-145

    halign = center
    valign = center
}
```

