 --  animations.lua  autostart.lua  env.lua  input.lua  keybindings.lua  look.lua  misc.lua  monitor.lua  window.lua  window_rule.lua
require("modules.monitor")
require("modules.animations")
require("modules.autostart")
require("modules.env")
require("modules.keybindings")
require("modules.look")
require("modules.misc")
require("modules.window")
require("modules.window_rule")
