foreground #e3e1e9
background #121318
selection_foreground #dde1f9
selection_background #414659

cursor #b5c4ff
cursor_text_color background

url_color #b5c4ff

active_border_color #b5c4ff
inactive_border_color #8f909a
bell_border_color #e2bbdb

scrollbar_handle_color #8f909a
scrollbar_track_color #1e1f25

color0  #121318
color1  #ffb4ab
color2  #b5c4ff
color3  #e2bbdb
color4  #b5c4ff
color5  #c1c5dd
color6  #e2bbdb
color7  #e3e1e9

color8  #8f909a
color9  #93000a
color10 #344479
color11 #5b3d57
color12 #b5c4ff
color13 #414659
color14 #5b3d57
color15 #38393f