fastfetch 
font_family JetBrainsMono Nerd Font 
font_size  13

shell                          fish  
shell_integration              enabled

cursor_shape beam
cursor_blink_interval 0
window_padding_width 12

# Enable cursor trail
cursor_trail 100

cursor_trail_decay 0.05 0.3

cursor_trail_start_threshold 2


disable_ligatures              yes
enable_audio_bell              no

remember_window_size           no
background_opacity 0.75
dynamic_background_opacity yes
scrollbar_track_opacity        0
scrollbar_track_hover_opacity  0

hide_window_decorations yes

allow_remote_control yes
listen_on unix:@kitty

# Closing confirmation 
confirm_os_window_close        0

sync_to_monitor                no
# Cursor colors
cursor #7C91FF
cursor_text_color background

# Scrollbar colors
scrollbar_handle_color  #939ab7
scrollbar_track_color   #494d64

# URL color when hovering with mouse

copy_on_select yes

strip_trailing_spaces smart

mouse_hide_wait 1.5

repaint_delay 10

input_delay 3


scrollback_lines 50000
# Kitty window border colors
active_border_color #7096FF
inactive_border_color #233A68
bell_border_color       #eed49f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system


include ~/.config/matugen/generated/kitty.conf
