hl.on("hyprland.start", function () 
   hl.exec_cmd("waybar")
   -- hl.exec_cmd("awww-daemon")
   hl.exec_cmd("swaync")
   hl.exec_cmd("hyprctl setcursor catppuccin-macchiato-lavender-cursors 21")
   hl.exec_cmd("~/.config/hypr/start-wallpaper.sh")	
end)
